id: task_contact_info_corporate
name: Corporate Contact Information
description: Collect contact information for corporate entities
version: 1

extends: _base/contact_info_base         # Inherit email and phone from base

component_id: form

schema:
  fields:
    # Corporate-specific field: Legal Name
    - name: legal_name
      label: "Legal Business Name"
      type: text
      required: true
      placeholder: "Acme Corporation"
      helpText: "Official registered business name as it appears on incorporation documents"
      validation:
        minLength: 2
        maxLength: 200
        pattern: "^[a-zA-Z0-9\\s.,'-]+$"

    # Corporate-specific field: Entity Type
    - name: entity_type
      label: "Entity Type"
      type: select
      required: true
      helpText: "Select your business legal structure"
      options:
        - value: corporation
          label: "Corporation (C-Corp or S-Corp)"
        - value: llc
          label: "Limited Liability Company (LLC)"
        - value: partnership
          label: "Partnership (GP or LP)"
        - value: sole_proprietorship
          label: "Sole Proprietorship"

    # Corporate-specific field: Jurisdiction
    - name: jurisdiction
      label: "Jurisdiction of Incorporation"
      type: select
      required: true
      helpText: "Where is the business legally registered?"
      options:
        - value: US
          label: "United States"
        - value: CA
          label: "Canada"
        - value: GB
          label: "United Kingdom"
        - value: AU
          label: "Australia"

    # Renamed inherited field: business_email (inherits from base email)
    - name: business_email
      inherits: email                    # Copy definition from base email field
      label: "Business Email Address"    # Override label
      placeholder: "contact@acmecorp.com"
      helpText: "Primary business contact email"

    # Renamed inherited field: business_phone (inherits from base phone)
    - name: business_phone
      inherits: phone                    # Copy definition from base phone field
      label: "Business Phone Number"     # Override label
      placeholder: "+1 (555) 123-4567"
      helpText: "Primary business contact number"

    # Optional field with conditional visibility
    - name: incorporation_date
      label: "Date of Incorporation"
      type: date
      required: false
      helpText: "When was the business officially registered?"
      visible: "entity_type in ['corporation', 'llc']"
      validation:
        max: "today"

  layout: two-column
  submitLabel: "Continue to Documents"
  cancelLabel: "Save Draft"

expected_output_fields:
  - legal_name
  - entity_type
  - jurisdiction
  - business_email
  - business_phone
  - incorporation_date

tags:
  - contact-info
  - corporate
  - kyc
